"""Initial migration

Revision ID: 51271137641d
Revises: 
Create Date: 2025-09-29 22:31:30.224647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51271137641d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
